from __future__ import annotations

from typing import Any, Dict, List, Optional, Literal
from pydantic import BaseModel, ConfigDict, Field


class Turn(BaseModel):
    """
    Objective:
    Represents a single unit of dialogue in the conversation timeline.

    - Acts as the canonical record of who produced content at a specific turn.
    - Used by decision and generation modules as the primary conversational context.
    - Preserves strict ordering of discussion for traceability and replay.
    """

    turn_index: int = Field(
        ...,
        description="Zero-based index of this turn in the full conversation timeline.",
    )
    participant_id: str = Field(
        ...,
        description="Unique participant identifier for the actor associated with this turn record.",
    )
    participant_type: Literal["agent", "system"] = Field(
        ...,
        description="Origin of the turn; 'agent' for discussion participants and 'system' for host or control messages.",
    )
    content: str = Field(
        ...,
        description="Raw text content spoken or emitted for this turn.",
    )


class ReplyResult(BaseModel):
    """
    Objective:
    Encapsulates the output of the reply generation phase.

    - Separates the actual reply from meta-intent.
    - Enables logging and debugging of the generated response purpose.
    - Keeps reply output minimal and structured.
    """

    reply: str = Field(
        ...,
        description="Primary reply text generated by an agent for the current speaking turn.",
    )
    intent: str = Field(
        default="",
        description="Short explanation of the reply purpose or speaking intent, mainly for trace and debugging.",
    )


class SubtopicPlan(BaseModel):
    """
    Objective:
    Defines the structure and lifecycle of a subtopic within a discussion session.

    - Breaks the session topic into smaller focused discussion units.
    - Gives the host and agents a concrete target for the current phase.
    - Tracks whether a subtopic is pending, active, or complete.
    """

    subtopic_id: str = Field(
        ...,
        description="Stable identifier for the subtopic, used to track it across the session.",
    )
    title: str = Field(
        ...,
        description="Human-readable title of the subtopic discussed in the session.",
    )
    kickoff_message: str = Field(
        ...,
        description="Host message used to open and frame this subtopic at the start of its turn loop.",
    )
    achievement: str = Field(
        ...,
        description="Expected outcome or completion target for this subtopic.",
    )
    conclusion: str = Field(
        ...,
        description="Closing summary or resolved result for this subtopic after discussion finishes.",
    )
    status: Literal["PENDING", "ONGOING", "FINISH"] = Field(
        default="PENDING",
        description="Lifecycle state of the subtopic: waiting, active, or completed.",
    )


class DiscussionParticipant(BaseModel):
    """
    Objective:
    Defines the static identity and behavioral configuration of a participant.

    - Serves as the base abstraction for discussion participants.
    - Encapsulates role, traits, and knowledge used to condition LLM behavior.
    - Provides stable participant metadata for orchestration and prompt building.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    participant_id: str = Field(
        ...,
        description="Unique identifier for the participant, used as the canonical key in runtime state and turn records.",
    )
    display_name: str = Field(
        ...,
        description="Readable participant name shown in logs, prompts, and exported discussion artifacts.",
    )
    role: str = Field(
        ...,
        description="Functional role of the participant in the discussion, used to shape perspective and replies.",
    )
    kind: Literal["agent", "system"] = Field(
        default="agent",
        description="Participant category; typically 'agent' for speakers and 'system' for host-like participants.",
    )
    traits: List[str] = Field(
        default_factory=list,
        description="Behavioral traits or speaking tendencies used to condition discussion style and priorities.",
    )
    goal: List[str] = Field(
        default_factory=list,
        description="Participant objectives that describe what perspective or responsibilities the participant should cover.",
    )
    base_knowledge: List[str] = Field(
        default_factory=list,
        description="Background knowledge, assumptions, or domain context available to the participant for generation.",
    )
    can_self_generate: bool = Field(
        default=True,
        description="Whether this participant can autonomously generate replies when selected as the next speaker.",
    )


class AgentSpec(DiscussionParticipant):
    """
    Objective:
    Extends DiscussionParticipant with execution-level LLM configuration.

    - Binds concrete models to the participant.
    - Separates reply generation from summary generation responsibilities.
    - Controls prompt history size for runtime efficiency.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    reply_llm: Any = Field(
        ...,
        description="Language model instance used to generate the agent's spoken reply.",
    )
    summary_llm: Any = Field(
        ...,
        description="Language model instance used to refresh the agent summary after turns.",
    )
    max_history_turns: int = Field(
        default=20,
        description="Maximum number of recent turns included in prompts for this agent when building context.",
    )


class ParticipantRuntimeState(BaseModel):
    """
    Objective:
    Maintains mutable per-participant runtime state during the session.

    - Tracks speaking activity and most recent reply.
    - Stores the latest refreshed summary for the participant.
    - Holds unresolved questions and current focus for subsequent reply generation.
    """

    times_spoken: int = Field(
        default=0,
        description="Count of how many times this participant has spoken in agent turns so far.",
    )
    last_spoken_turn_index: Optional[int] = Field(
        default=None,
        description="Turn index of the participant's most recent spoken turn, or None if the participant has not spoken yet.",
    )
    latest_reply: str = Field(
        default="",
        description="Most recent reply text generated by this participant.",
    )
    status: Literal["ONGOING", "FINISH"] = Field(
        default="ONGOING",
        description="Simplified runtime status kept mainly for compatibility with prior examples and debug output.",
    )
    summary_text: str = Field(
        default="",
        description="Latest refreshed summary for this participant, replaced on each summary update rather than accumulated as a list.",
    )
    latest_open_questions: List[str] = Field(
        default_factory=list,
        description="Outstanding questions currently associated with this participant's perspective or unresolved work.",
    )
    current_focus: Optional[str] = Field(
        default=None,
        description="Current focus area or active line of thought inferred for this participant.",
    )


class TurnSnapshot(Turn):
    """
    Objective:
    Captures a point-in-time snapshot of a participant's runtime state during a turn.

    - Extends the base turn record with snapshot-specific runtime metadata.
    - Preserves a historical trace of participant state changes.
    - Supports export, debugging, and turn-by-turn inspection.
    """

    latest_message_index: Optional[int] = Field(
        default=None,
        description="Latest turn index associated with this participant at snapshot time.",
    )
    summary: Optional[str] = Field(
        default=None,
        description="Latest summary text recorded for the participant at snapshot time.",
    )
    latest_open_questions: List[str] = Field(
        default_factory=list,
        description="Snapshot copy of the participant's currently open questions at this turn.",
    )


class ConversationState(BaseModel):
    """
    Objective:
    Serves as the single source of truth for the entire multi-agent discussion session.

    - Aggregates the topic, subtopics, turns, and participant runtime states.
    - Enables deterministic orchestration across decision and generation phases.
    - Provides a replayable and exportable record of the session.
    """

    topic: str = Field(
        ...,
        description="Top-level discussion topic for the whole multi-agent session.",
    )
    achievement: str = Field(
        ...,
        description="Overall session objective or target outcome the discussion is expected to reach.",
    )
    subtopics: List[SubtopicPlan] = Field(
        default_factory=list,
        description="Ordered list of subtopics planned or generated for the session.",
    )
    current_subtopic_index: int = Field(
        default=0,
        description="Index of the currently active subtopic within the subtopics list.",
    )
    turns: List[Turn] = Field(
        default_factory=list,
        description="Chronological list of all turns produced during the session.",
    )
    participant_states: Dict[str, ParticipantRuntimeState] = Field(
        default_factory=dict,
        description="Runtime state map keyed by participant_id for tracking discussion progress and recent activity.",
    )
    turn_snapshots: List[TurnSnapshot] = Field(
        default_factory=list,
        description="Historical snapshots of participant runtime state captured after turns.",
    )

    @property
    def last_turn(self) -> Optional[Turn]:
        return self.turns[-1] if self.turns else None

    def append_turn(
        self,
        participant_id: str,
        participant_type: Literal["agent", "system"],
        content: str,
    ) -> Turn:
        turn = Turn(
            turn_index=len(self.turns),
            participant_id=participant_id,
            participant_type=participant_type,
            content=content,
        )
        self.turns.append(turn)
        return turn

    def append_snapshot(
        self,
        *,
        turn_index: int,
        participant_id: str,
        participant_type: Literal["agent", "system"],
        content: str,
        latest_message_index: Optional[int],
        summary: Optional[str],
        latest_open_questions: List[str],
    ) -> None:
        self.turn_snapshots.append(
            TurnSnapshot(
                turn_index=turn_index,
                participant_id=participant_id,
                participant_type=participant_type,
                content=content,
                latest_message_index=latest_message_index,
                summary=summary,
                latest_open_questions=latest_open_questions,
            )
        )

    def ensure_participant_state(
        self,
        participant_id: str,
    ) -> ParticipantRuntimeState:
        if participant_id not in self.participant_states:
            self.participant_states[participant_id] = ParticipantRuntimeState()
        return self.participant_states[participant_id]

    def get_participant_state(
        self,
        participant_id: str,
    ) -> ParticipantRuntimeState:
        return self.ensure_participant_state(participant_id)
